### PR TITLE
Fix nested anchors

### PR DESCRIPTION
**Pull request by superstator**

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @superstator ,

Thank you, I will try to look at it during the weekend,

Best Regards,

Jonathan

**Comment by superstator** [comment]
Thanks, just let me know if i can do any more with it. FWIW, I dropped a debug build into our scraping system and it made an enormous difference - much less junk data coming out when we query for links via xpath. One particularly crummy example went from 411mb of link text to 36mb!

**Comment by JonathanMagnan** [comment]
Hello @superstator ,

We didn't merge your pull request since we started to fix issue similar to this one in another way.

A fix should be available on Monday.

It will not require having the option `OptionFixNestedTags` enabled as this kind of issue should be fixed by default.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @superstator ,

The v1.6.0-beta1 has been released which should fix anchor problem.

Please re-open the issue #53 if you still have some problem.

Best Regards,

Jonathan

**Pull request closed without merging**
