### PR TITLE
Minor performance and GC traffic optimizations

### PR DESCRIPTION
**Pull request by ZimM-LostPolygon**
Mainly reduced throwaway strings allocations, and used Dictionary.TryGetValue where possible to avoid double lookup.

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @ZimM-LostPolygon ,

Thank you for your contribution,

I will try to check it and merge your pull this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ZimM-LostPolygon ,

I started to review this pull. Unfortunately, I will not be able to add it on this week release since some stuff must be reviewed.

By example, adding a new variable `_optimizedName` is a very bad idea. It's true it will be faster, but the object size will also be bigger which cause some impact when parsing large HTML. By example, this guy (Issue #77) have some millions attribute in his HTML.

However, there is a lot of change that for sure improve the performance in this pull such `TryGetValue`.

Best Regards,

Jonathan

**Comment by ZimM-LostPolygon** [comment]
@JonathanMagnan 
`_optimizedName` is not an invention  of mine :) This pattern was already used in `HtmlNode` class, I just applied it to `HtmlAttribute` as well.

**Comment by anish714** [comment]
Just fyi, there is not a whole lot of difference between ContainsKey and TryGetValue.
If you look at the dictionary source code, [http://referencesource.microsoft.com/#mscorlib/system/collections/generic/dictionary.cs,bcd13bb775d408f1](http://referencesource.microsoft.com/#mscorlib/system/collections/generic/dictionary.cs,bcd13bb775d408f1)

you'll see that TryGetValue basically contains ContainsKey inside it.

**Comment by ZimM-LostPolygon** [comment]
Or course it does. But when using TryGetValue, you only have to do a single
lookup instead of two.

**Comment by JonathanMagnan** [comment]
Hello @ZimM-LostPolygon ,

Most of your fix has been added.

## _optimizedName
This optimization has not been added for `memory` reason. Adding a new string will take a lot more space for some people.

As you said, this `trick` is used in another place, perhaps one day it will get removed!

## OptionLowerCaseWhenParsing 
This tag could have some side effect. The default behavior was to always lower but with this options, we need to enable it for the `ToLowerInvariant` apply.

Even if we enable it by default, due to some side effect, I believe this optimization have too much risk.

## ImplicientEnd && ExplicitEnd
Doesn't make sense anymore without the `OptionLowerCaseWhenParsing` since the value is always in `lower`.

## HtmlResetters 
Instead of using a `KeyValuePair`, a dictionary has been used. That's true your fix is currently faster due to the number of rows. However, depending on some future direction, that `HtmlResetters` can growth a lot in size so it probably better to set it right now as a dictionary then doing it later. So in short, we made your suggested changes with a dictionary instead.

Good job for all changes and thank a lot for your contribution ;)

I believe all your accepted changes will improve the library.

Best Regards,

Jonathan
---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @ZimM-LostPolygon ,

I will close this pull since your fixes are already been released beside one that I have commented.

Thank a lot for your contribution.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Pull request closed without merging**
