### PR TITLE
Feature/139 html node.write virtual

### PR DESCRIPTION
**Pull request by DzonnyDZ**
This is solving issue #139 

Hello there,
We have been using HtmlAgilityPack in our company for several years. Thinking it's dead we maintained our own copy. Now I see you started to take care of it and I would like the changes we have done to be integrated to the main repository. This is the smallest one.
We did several changes (or rather fixes) to HtmlAgilityPack code especially to fix compatibility issues with XSLT and XPath. Also to solve sometimes some issues with encoding. So unless these issues are already fixed, I would make more pull requests - if this is the way we can cooperate. If you have any other suggestion, I'm in.

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @DzonnyDZ ,

Thank you for the pull, we will make the merge this week.

Feel free to provide more pull but please keep them short. While we are happy to support this library, we can only put a few hours every week on it.

Do you think we could have access to your main `HtmlAgilityPack` repository? Perhaps we could look on all changes your have done so far.

Best Regards,

Jonathan

**Comment by DzonnyDZ** [comment]
Hello,
Unfortunately I cannot provide you access to the repository where our changes are. But I uploaded the changes here: https://github.com/DzonnyDZ/HtmlAgilityPack-RFE. But be aware that these are the changes done to some old version of HTML Agility Pack and I don't think they can be just merged with current status of the code.

My idea was that I will now do tests and see if the latest version of HtmlAgilityPack contains any bugs which we have been fixing. And in case of bugs found I'd make additional pull requests. Unfortunately I also cannot fully dedicate to this, so I cannot speak how fast I will do that. I'll definitely keep the pull requests short.

I think HtmlAgilityPack is great library and I definitely want to use it in future, so I want it to support all possible scenarios and I want to contribute to that.
Thank you for taking care of HAP.

**Comment by JonathanMagnan** [comment]
Hello @DzonnyDZ ,

Thank you, I will have my programmer on Thursday to compare both repositories and check if there is some easy fix/merge he can do.

I guess we will have a better idea when he will start to check your repository.

No problem, we try our best to add value to the .NET Community ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @DzonnyDZ ,

The v1.6.17 has been released.

We also reviewed your repository and some fix will be probably added soon from it ;)

Thank a lot.

Best Regards,

Jonathan

**Pull request merged**
