### PR TITLE
Improve Encapsulator

### PR DESCRIPTION
**Pull request by parsalotfy**
Hello ,
When I pulled Encapsulator to this project , I forgot something : Exception Handling.
In this pull request I have not added just Exception Handling but it is the most important one.
Summary :

1. **Exception Handling**
GetEncapsulatedData is one method , so when HAP user call it , if the XPath of developer is wrong or the types of properties in their classes are not valid , they just see an unhandled exception or format exception or null refrence exception !
BUT they don't know which part of their code are written wrong...
With new version of Encapsulator , There is lots of Exception handling , so there is not unclear exceptions anymore.

2. **Overloads**
With making GetEncapsulatedData , 2 overload , I became able to remove and clean unnecessary reflection codes , so it helps to improve performance of Encapsulator.

3. **Tools**
I added some methods to Tools class , and also remove some.
for example I simulate Func delegate in C# 3.0 or Where extension method in Linq
AND make all of the methods in Tools , and Tools class it self , INTERNAL.
So HAP user will not became distracted of extension methods.

4. **Compatibility**
After this additions and removal , The Encapsulator is already Compatible with all versions of HAP you have targeted to like .Net 2.0 or .Net Standard 1.3 .

Here is List of Exceptions may Encapsulator Throw :
* ArgumentNullException
* MissingMethodException
* MissingXPathException
* NodeNotFoundException
* NodeAttributeNotFoundException
* FormatException
* Exception

If there is a problem in my codes , Please let me know them to fix them.
Thank you in advance for your open source library.

Parsa

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Thank a lot,

I will try to get my developer reviewing your pull next week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ashishsapkale ,

Your change has been merged.

The v1.7.3 has been released.

Thank you for your contribution ;)

If you improve again your Encapsulator, please try to add some `unit test`. It will make me feel safer to release changes you are doing.

Best Regards,

Jonathan

**Comment by parsalotfy** [comment]
Hello,
Thank you for merging the pull request.
I have some questions :

> If you improve again your Encapsulator, please try to add some unit test. 
 
You added unit-test of Encapsulator in this [commit](https://github.com/zzzprojects/html-agility-pack/commit/b10147d3ad158407be963f7d6315fd39a2109673) , is it not enough ?
I was wondering if I add unit-test to my pull requests , and you merge it , it may mess up the HAP library.
Please let me know if there is no problem by adding unit test , and creating pull request of entire addition , including unit-test .

And is it important that entire additions be in **1 Commit** ?
I mean I created lots of commits when I was working on Encapsulator but I merged HAP again and push those additions in One Commit , then I created pull request.
If there is no problem by number of commits , I can commit every time I add or delete something and in this way I can explain every change.

If too much commiting is not a good idea ( maybe messing up the commits part of Repository ) , let me know if there is better idea. or I will work on it with current way.


Thanks a lot for letting me contribute in HAP Repository and dedicating time to it.

Parsa

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

> You added unit-test of Encapsulator in this commit , is it not enough ?

More unit test is always good ;) Yes, we already have some unit test, I just mean if you add some new stuff, adding unit tests with it will be great.

You can create your own file of unit test in the test project, so we will never touch it and everything should be fine.

> And is it important that entire additions be in 1 Commit ?

Having small changes is always easier than a big pull of change to reviews. For example, I don't mind releasing this library every Monday. On my side, I prefer multiple pull over a big one.

By the way, could you provide me your personal email to me in case of more personal question or sometimes a question so we could reach you easier: info@zzzprojects.com

> Thanks a lot for letting me contribute in HAP Repository and dedicating time to it.

Thank to you to add value to this library ;)

Best Regards,

Jonathan

**Pull request merged**
