### PR TITLE
Encapsulator

### PR DESCRIPTION
**Pull request by parsalotfy**
Hi
I was wondering what if we can **use HAP like ORM's**. 
It really improves Developer Experience !
So we could create entities and with writting some little code , the HAP gives us all data in **structural format**.
Then I fork HAP and start adding **reflection** to it.
I just add a method to HtmlDocument.DocumentNodes , like SelectSingleNode and so on.
In samples folder I added 2 sample-project to show how my method works.
Also I create my method in the way that **it supports .NetStandard1.6 and .NetFramework2.0**
In some cases( ex: [Huge memory consumption](https://github.com/zzzprojects/html-agility-pack/issues/77) ) the reflection and generic causes performance overhead , but in these cases developer can leave my method and use main methods.
In simple cases and projects I found Encapsulation duration , low in comparison of Loading Page !
By the way , I just wanted to make using HAP more and more interesting and easy for developers.
It's my pleasure to have the chance to contribute in this project.

Best Regards,

Parsa

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy 

Thank you for your contribution.

I will soon have a developer more dedicated to open source project. It may take a few week but I will have him to check your pull when he will be more comfortable with HAP code.

Best Regards,

Jonathan

**Comment by parsalotfy** [comment]
Hello @JonathanMagnan 
Good time :)
I just wanted to let me know if you checked out my pull request or not.
And if it has problems , I will be happy to let me know them,
Thank you.

Parsa

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

Sorry for the delay, I will have my developer look at it this week and give you his feedback.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

My developer and I looking for your additions, that's for sure a great new feature ;)

We couldn't merge your code into GitHub since we currently try to make some cleanup but we included the most important part (The encapsulator).

Let me know if everything works as you expected.

Thank a lot for your contribution.

Best Regards,

Jonathan

**Comment by parsalotfy** [comment]
Hello.
Thank you for accepting my code.
Hope it makes developers more satisfied and comfort of HAP.
I try to make Encapsulator better.
Good Luck!
Parsa

**Comment by JonathanMagnan** [comment]
Yup, I'm pretty sure that's a great addition.

In a few months, we will re-write fully our documentation and make sure people know about this new features you added ;)

Best Regards,

Jonathan

**Pull request closed without merging**
