### PR TITLE
Update HtmlTextNode.cs

### PR DESCRIPTION
**Pull request by ashishsapkale**
For HtmlTextNode, User can set the text value, after setting this value UpdateHtml method should get call, as user is changing text then if should reflect in InnerHtml and OuterHtml of DocumentNode. So called **SetChanged** method in setter of property string Text

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @ashishsapkale ,

I believe your pull is missing your change.

It look only end region name has been modified.

Best Regards,

Jonathan

**Comment by ashishsapkale** [comment]
In **setter method of "Text"** property, I have made call to **SetChanged** method, this is the only change. 
I have CodeMaid extension for my Visual Studio, I think it has set End region texts.

**Comment by JonathanMagnan** [comment]
Oh sorry, it must have been late.

I just saw the change.

Thank you, we will review it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ashishsapkale ,

Your change has been merged.

The v1.7.3 has been released.

Thank you for your contribution.

Best Regards,

Jonathan

**Pull request merged**
