### PR TITLE
Encoding definition improvement

### PR DESCRIPTION
**Pull request by SMishanya**
Current version of HAP allows to determine HTML-page encoding for such meta tags:
`<meta http-equiv="content-type" content="text/html;charset=iso-8859-1"/>`
But in HTML5 next tag is also a valid one:
 `<meta charset="iso-8859-1"/>`

Added appropriate changes to support second case.

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @SMishanya ,

Thank a lot for your pull,

My developer will check it very soon.

Best Regards,

Jonathan

**Comment by jfcardinal** [comment]
Minor point: I suggest updating the &lt;summary&gt; for HtmlDocument.DeclaredEncoding at line 236. It describes the pre-HTML5 tag:

"Declared encoding is determined using the meta http-equiv="content-type" content="text/html;charset=XXXXX" html node."

I would omit describing the details of the HTML element. The details are not necessary for someone using the facility, and the code that implements the behavior is far away in the source file.

Another option is to add the details for the HTML5 version, perhaps something like this:

"Declared encoding is determined using the meta http-equiv="content-type" content="text/html;charset=XXXXX" html node (pre-HTML5) or the meta charset="XXXXX" html node (HTML5)."

**Comment by JonathanMagnan** [comment]
Hello @SMishanya , @jfcardinal ,

The pull has been merged. We also made your suggestion @jfcardinal to improve the description.

A new release will be available later today.

Thank both of you for your contribution.

Best Regards,

Jonathan

**Comment by SMishanya** [comment]
Hello @JonathanMagnan,

Thank you too

**Comment by JonathanMagnan** [comment]
The v1.7.2 has been released ;)

Best Regards,

Jonathan

**Pull request merged**
